'use client';

import { useCampaign } from '@/context/CampaignContext';
import { useRouter } from 'next/navigation';
import {
    Sparkles,
    ArrowLeft,
    Eye,
    Send,
    CheckCircle2,
    Clock,
    RefreshCcw,
    Mail,
    User,
    Users,
    Calendar,
    Target
} from 'lucide-react';
import ProgressIndicator from '@/components/ProgressIndicator';

export default function AIContentGenerationPage() {
    const { campaignData } = useCampaign();
    const router = useRouter();

    // Mock generated content structure
    const subject = `Revolutionizing ${campaignData.aiStrategyInput.split(' ')[0] || 'Marketing'} with AI`;
    const body = `Hi [Contact Name],\n\nI noticed your interest in ${campaignData.aiStrategyInput.split(' ').slice(1, 4).join(' ') || 'high-end solutions'} and wanted to reach out. Our team at ${campaignData.aiStrategyInput.split(' ').pop()?.replace('.', '') || 'Persona'} has developed a platform that specifically addresses the needs of professionals in your field.\n\nBased on your profile, I believe our AI-driven approach to personalization could significantly boost your click-through rates and overall engagement.\n\nWould you be open to a 10-minute chat next week to see how this fits into your current workflow?\n\nBest regards,\n[Your Name]`;

    return (
        <div className="min-h-[calc(100vh-80px)] bg-[#FDFDFD] px-8 py-10 animate-in fade-in slide-in-from-bottom-4 duration-700">
            <div className="max-w-7xl mx-auto space-y-8">
                {/* Header */}
                <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
                    <div>
                        <button
                            onClick={() => router.back()}
                            className="flex items-center gap-2 text-sm text-gray-400 hover:text-gray-600 transition-colors font-medium mb-4 group"
                        >
                            <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
                            Back to Strategist
                        </button>
                        <div className="flex items-center gap-3">
                            <div className="p-2.5 bg-indigo-600 rounded-xl text-white shadow-lg shadow-indigo-100">
                                <Sparkles className="w-6 h-6" />
                            </div>
                            <h1 className="text-3xl font-bold text-gray-900">AI Email Content Generation</h1>
                        </div>
                        <p className="text-gray-500 font-medium mt-1 ml-1">Review your email content generated by AI for &rsquo;{campaignData.name}&rsquo;</p>
                    </div>

                    <div className="flex items-center gap-3">
                        <button className="flex items-center gap-2 px-6 py-3 bg-white border border-gray-100 rounded-xl text-sm font-bold text-gray-600 hover:bg-gray-50 transition-all shadow-sm">
                            <RefreshCcw className="w-4 h-4" />
                            Regenerate
                        </button>
                        <button className="flex items-center gap-2 px-8 py-3 bg-gradient-to-r from-indigo-600 to-indigo-700 text-white rounded-xl text-sm font-bold hover:shadow-lg hover:shadow-indigo-100 transition-all hover:-translate-y-0.5 shadow-indigo-50">
                            Launch Campaign <Send className="w-4 h-4" />
                        </button>
                    </div>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
                    {/* Left Column - Strategy & Editor (8 cols) */}
                    <div className="lg:col-span-8 space-y-8">
                        {/* AI Generated Content Section (Show user input from Step 1) */}
                        <div className="bg-white rounded-[32px] border border-gray-100 shadow-sm overflow-hidden">
                            <div className="p-8 border-b border-gray-50 bg-indigo-50/20">
                                <h2 className="text-lg font-bold text-gray-900 flex items-center gap-2">
                                    <Target className="w-5 h-5 text-indigo-600" />
                                    AI Generated Content
                                </h2>
                                <p className="text-xs text-gray-400 font-bold uppercase tracking-wider mt-1">Based on your input in Step 1</p>
                            </div>
                            <div className="p-8">
                                <div className="p-6 bg-gray-50 rounded-2xl border border-gray-100">
                                    <p className="text-sm text-gray-600 leading-relaxed italic">
                                        &ldquo;{campaignData.aiStrategyInput || 'No input provided from the strategist stage.'}&rdquo;
                                    </p>
                                </div>
                            </div>
                        </div>

                        {/* Email Content Preview/Editor */}
                        <div className="bg-white rounded-[32px] border border-gray-100 shadow-sm overflow-hidden">
                            <div className="p-8 border-b border-gray-50 flex items-center justify-between">
                                <div className="flex items-center gap-4">
                                    <div className="w-10 h-10 bg-indigo-50 rounded-xl flex items-center justify-center text-indigo-600">
                                        <Mail className="w-5 h-5" />
                                    </div>
                                    <h2 className="text-lg font-bold text-gray-900">Email Draft</h2>
                                </div>
                                <div className="flex items-center gap-2">
                                    <span className="px-3 py-1 bg-emerald-50 text-emerald-600 text-[10px] font-black rounded-full border border-emerald-100">AI OPTIMIZED</span>
                                </div>
                            </div>

                            <div className="p-10 space-y-8">
                                <div className="space-y-4">
                                    <div className="flex items-start gap-4 pb-4 border-b border-gray-50">
                                        <span className="text-xs font-bold text-gray-400 w-16 pt-1 uppercase">Subject</span>
                                        <p className="text-sm font-bold text-gray-900">{subject}</p>
                                    </div>
                                    <div className="pt-4">
                                        <div className="whitespace-pre-wrap text-sm text-gray-600 leading-relaxed font-medium">
                                            {body}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Right Column - Stats & Preview (4 cols) */}
                    <div className="lg:col-span-4 space-y-8 sticky top-28">
                        {/* Quick Stats Card */}
                        <div className="bg-white rounded-[32px] p-8 border border-gray-100 shadow-sm space-y-6">
                            <h3 className="text-sm font-black text-gray-900 uppercase tracking-widest">Campaign Overview</h3>

                            <div className="space-y-4">
                                <div className="flex items-center justify-between p-4 bg-gray-50 rounded-2xl border border-gray-100">
                                    <div className="flex items-center gap-3">
                                        <Users className="w-4 h-4 text-indigo-500" />
                                        <span className="text-xs font-bold text-gray-500">Recipients</span>
                                    </div>
                                    <span className="text-sm font-bold text-gray-900">1,250</span>
                                </div>
                                <div className="flex items-center justify-between p-4 bg-gray-50 rounded-2xl border border-gray-100">
                                    <div className="flex items-center gap-3">
                                        <Calendar className="w-4 h-4 text-indigo-500" />
                                        <span className="text-xs font-bold text-gray-500">Scheduled</span>
                                    </div>
                                    <span className="text-sm font-bold text-gray-900">Immediate</span>
                                </div>
                            </div>

                            <div className="pt-2">
                                <ProgressIndicator step={3} totalSteps={3} percentage={100} />
                            </div>

                            <button className="w-full flex items-center justify-center gap-2 py-4 bg-indigo-50 text-indigo-600 rounded-xl text-sm font-bold hover:bg-indigo-100 transition-all group">
                                <Eye className="w-4 h-4 group-hover:scale-110 transition-transform" />
                                Preview for all Contacts
                            </button>
                        </div>

                        {/* AI Tips */}
                        <div className="bg-indigo-600 rounded-[32px] p-8 text-white shadow-xl shadow-indigo-100">
                            <div className="flex items-center gap-3 mb-4">
                                <Sparkles className="w-5 h-5 text-indigo-200" />
                                <h4 className="font-bold">AI Insight</h4>
                            </div>
                            <p className="text-sm text-indigo-100 leading-relaxed font-medium">
                                We&apos;ve added a custom hook in the first sentence to increase engagement. Our models predict a <span className="text-emerald-300 font-bold">24% higher open rate</span> with this version.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
